MvcCoreGiris/Models/ErrorViewModel.cs
using System;

namespace MvcCoreGiris.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreGiris/Models/Kisi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreGiris.Models
{
    public class Kisi
    {
        public int Id { get; set; }

        [Required, DisplayName("Kişi Adı")]
        public string KisiAd { get; set; }
    }
}

MvcCoreGiris/Models/OkulDbContex.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreGiris.Models
{
    public class OkulDbContex : DbContext
    {
        public OkulDbContex(DbContextOptions<OkulDbContex> options) : base (options)
        {

        }

        //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    optionsBuilder.UseSqlServer("server=.; database=OkulContex; Integrated Security = true;");
        //}

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Kisi>().HasData(
                new Kisi {Id = 1, KisiAd = "Burak" },
                new Kisi {Id = 2, KisiAd = "Osman" },
                new Kisi {Id = 3, KisiAd = "Büşra" }
                );
        }
        public DbSet<Kisi> Kisiler { get; set; }
    }
}

MvcCoreGiris/Components/SansliKisiViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Rename;
using Microsoft.EntityFrameworkCore;
using MvcCoreGiris.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MvcCoreGiris.Components
{
    public enum TextColor { danger, info, warning, success, primary, secondary, dark, light}
    public class SansliKisiViewComponent : ViewComponent
    {
        private readonly OkulDbContex okulDbContex;

        public SansliKisiViewComponent(OkulDbContex okulDbContex)
        {
            this.okulDbContex = okulDbContex;
        }
        public async Task<IViewComponentResult> InvokeAsync(TextColor renk)
        {
            var adet = await okulDbContex.Kisiler.CountAsync();
            var index = new Random().Next(adet);
            var kisi = await okulDbContex.Kisiler.Skip(index).FirstOrDefaultAsync();
            ViewBag.renk = Enum.GetName(renk.GetType(), renk);
            return View(kisi);
        }
    }
}

MvcCoreGiris/Controllers/HavaDurumuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcCoreGiris.Interfaces;

namespace MvcCoreGiris.Controllers
{
    public class HavaDurumuController : Controller
    {
        private readonly IWeatherService _weatherService;

        public HavaDurumuController(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SicaklikGetir(string sehirAd) {
            try
            {
                return Json(new { sicaklik = _weatherService.Temperature(sehirAd) });
            }
            catch (Exception)
            {

                return StatusCode(503);
            }
        }
    }
}

MvcCoreGiris/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcCoreGiris.Interfaces;
using MvcCoreGiris.Models;
using MvcCoreGiris.Services;

namespace MvcCoreGiris.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly LukyNumberService _lukyNumberService;
        public HomeController(ILogger<HomeController> logger, LukyNumberService lukyNumberService)
        {
            _logger = logger;
            _lukyNumberService = lukyNumberService;

        }

        public IActionResult Index()
        {
            ViewBag.SansliSayi = _lukyNumberService.LukyNumber;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreGiris/Controllers/KisilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcCoreGiris.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcCoreGiris.Controllers
{
    public class KisilerController : Controller
    {
        private readonly OkulDbContex _db;
        public KisilerController(OkulDbContex db)
        {
            _db = db;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(_db.Kisiler.ToList());
        }

        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(Kisi kisi)
        {
            if (ModelState.IsValid)
            {
                _db.Add(kisi);
                _db.SaveChanges();
                TempData["mesaj"] = $"\"{kisi.KisiAd}\"  adlı kişi başarıyla eklenmiştir.";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Duzenle(int? id)
        {
            var kisi = _db.Kisiler.Find(id);

            if (kisi != null)
            {
                return View(kisi);     
            }
            return NotFound();
        }
        
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Duzenle(Kisi kisi)
        {
            if (ModelState.IsValid)
            {
                //_db.Entry(kisi).State = Microsoft.EntityFrameworkCore.EntityState.Modified; //Altaki yontemin yerinede kullanılabılır.
                _db.Update(kisi);
                _db.SaveChanges();
                TempData["mesaj"] = $"\"{kisi.KisiAd}\" adlı kişi başarıyla düzenlenmiştir.";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Sil(int? id)
        {
            var kisi = _db.Kisiler.Find(id);

            if (kisi != null)
            {
                _db.Remove(kisi);
                _db.SaveChanges();
                TempData["mesaj"] = $"\"{kisi.KisiAd}\"  adlı kişi başarıyla silinmiştir.";
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }
    }
}

MvcCoreGiris/Views/HavaDurumu/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<h1>Hava Durumu</h1>
<form asp-action="SicaklikGetir" id="frmHavaDurumu">
    @*https://getbootstrap.com/docs/4.4/components/forms/#auto-sizing*@
    <div class="form-row align-items-center">
        <div class="col-sm-2 my-1">
            <label for="sehirAd" class="col-form-label">Şehir</label>
        </div>
        <div class="col-auto my-1">
            <input id="sehirAd" name="sehirAd" type="text" class="form-control" required />
        </div>
        <div class="col-auto my-1">
            <button type="submit" class="btn btn-primary">Getir</button>
        </div>
    </div>
    <div class="form-row align-items-center">
        <label class="col-sm-2 col-form-label">Sıcaklık</label>
        <label class="col-auto col-form-label">
            <span id="sicaklik"></span>
        </label>
    </div>
</form>

<hr />
<p class="font-weight-bold">Şehir adını yazar yazmaz sıcaklığı getirir.</p>
<form id="frmHavaDurumu2" asp-action="SicaklikGetir" class="form-inline">
    <label class="mb-2 mr-2">Şehir Adı:</label>
    <input id="sehirAd2" name="sehirAd" type="text" class="form-control mb-2 mr-2" placeholder="Şehir Adı" />
    <label id="sicaklik2" class="mb-2 mr-2">0°C</label>
</form>

@section scripts {
    <script>
        $("form#frmHavaDurumu2").submit(function (e) {
            e.preventDefault();
        });

        // ajax isteği yap
        function sicaklikGetir2() {
            var sehirAd = $("#sehirAd2").val().trim();

            if (!sehirAd) {
                $("#sicaklik2").text("");
                return;
            }

            var frm = $("form#frmHavaDurumu2");

            var url = frm.attr("action");
            var data = frm.serialize();
            $.post(url, data, function (result) {
                $("#sicaklik2").text(sehirAd + " iline ait hava sıcaklığı: " + result.sicaklik + "°C");
            }).fail(function () {
                $("#sicaklik2").text("");
            });
        }

        var lagSicaklikGetir2 = _.debounce(sicaklikGetir2, 500);

        $("#sehirAd2").on("input", lagSicaklikGetir2);

        $("form#frmHavaDurumu").submit(function (e) {
            e.preventDefault();
            var url = $(this).attr("action");
            var data = $(this).serialize();
            $.post(url, data, function (result) {
                $("#sicaklik").text(result.sicaklik + "°C");
            }).fail(function () {
                $("#sicaklik").text("Veri alınamadı.");
            });
        });
    </script>
}

MvcCoreGiris/Views/Home/Index.cshtml
@inject IWeatherService weatherService
@{
    ViewData["Title"] = "Home Page";
    string sicaklik;
    try
    {
        sicaklik = weatherService.Temperature("ankara") + "°C";
    }
    catch (Exception)
    {

        sicaklik = " İştenilen değerlere ulaşılamamıştır, Daha sonra tekrar deneyiniz!!";
    }
}

<div class="text-center ">
    <h1 class="display-4">Welcome</h1>

    <mesaj kapat-goster="true">Hoşgeldiniz. Şanslı Sayınız : @ViewBag.SansliSayi</mesaj>

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>@ViewBag.deneme</p>
    @if (sicaklik != null)
    {

    <div>Ankara'da Hava Sıcaklığı:@sicaklik</div>
    }
</div>

MvcCoreGiris/Views/Kisiler/Duzenle.cshtml
@model Kisi
@{
    ViewData["Title"] = "Duzenle";
}

<h1>Duzenle</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Duzenle">
            <input asp-for="Id" type="hidden"  />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KisiAd" class="control-label"></label>
                <input asp-for="KisiAd" class="form-control" />
                <span asp-validation-for="KisiAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-dark">Kaydet</button>
            </div>
        </form>
    </div>
</div>

MvcCoreGiris/Views/Kisiler/Index.cshtml
@model List<Kisi>
@{
    ViewData["Title"] = "Index";
}

<h1>Viewbag.Title</h1>


@if (TempData["mesaj"] != null)
{
    //class="alert alert-success"
<mesaj >
    @TempData["mesaj"]
</mesaj>

}

<a asp-action="Yeni" class="btn btn-outline-dark m-3 float-right"><i class="fas fa-plus p-1"></i>Yeni Kişi</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kişi Ad</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kisi in Model)
        {
            <tr>
                <td>@kisi.Id</td>
                <td>@kisi.KisiAd</td>
                <td>
                    <a asp-action="Duzenle" asp-route-id="@kisi.Id" class="btn btn-outline-dark"><i class="fas fa-edit p-2"></i></a>
                    <a href="#" class="btn btn-outline-danger" onclick="sil(@kisi.Id, '@kisi.KisiAd')"><i class="fas fa-trash p-2"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<form asp-action="Sil" name="silForm">
    <input type="hidden" name="id" />
</form>


@section scripts{ 

<script>
    function sil(id, kisiad) {
        event.preventDefault();
        if (confirm('"' + kisiad + '"adlı kişiyi silmek istediğinize eminmisiniz?')) {
            document.silForm.elements.id.value = id;
            document.silForm.submit();
        }
    }
</script>

}

MvcCoreGiris/Views/Kisiler/Yeni.cshtml
@model MvcCoreGiris.Models.Kisi

@{
    ViewData["Title"] = "Yeni";
}

<h1>Yeni</h1>

<h4>Kisi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Yeni">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KisiAd" class="control-label"></label>
                <input asp-for="KisiAd" class="form-control" />
                <span asp-validation-for="KisiAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-outline-dark float-right" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCoreGiris/Views/Shared/Components/SansliKisi/Default.cshtml
@model Kisi

<div>
    We <i class="fas fa-heart text-@ViewBag.renk"></i> @Model.KisiAd
</div>

MvcCoreGiris/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreGiris</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Welcome Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @*https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1*@
                        <li>
                            <vc:sansli-kisi renk="dark"></vc:sansli-kisi>
                            @await Component.InvokeAsync("SansliKisi", new { renk = TextColor.warning })

                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kisiler" asp-action="Index">Kişiler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HavaDurumu" asp-action="Index">Hava Durumu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MvcCoreGiris - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lodash.js/lodash.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>